In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.chdir("/content/drive/My Drive/FILE LATIHAN PYTHON/")

!pwd

/content/drive/My Drive/FILE LATIHAN PYTHON

In [3]:
os.chdir("/content/drive/My Drive/FILE LATIHAN PYTHON/flask-sqlite/csv2sqlite/")
!pwd

/content/drive/My Drive/FILE LATIHAN PYTHON/flask-sqlite/csv2sqlite

In [4]:
!pip install db-sqlite3

Collecting db-sqlite3
  Downloading db-sqlite3-0.0.1.tar.gz (1.4 kB)
Collecting db
  Downloading db-0.1.1.tar.gz (3.4 kB)
Collecting antiorm
  Downloading antiorm-1.2.1.tar.gz (171 kB)
     |████████████████████████████████| 171 kB 1.2 MB/s
Building wheels for collected packages: db-sqlite3, db, antiorm
  Building wheel for db-sqlite3 (setup.py) ... done
  Created wheel for db-sqlite3: filename=db_sqlite3-0.0.1-py3-none-any.whl size=1793 sha256=7b3eb60bd6c98c6b9e1cafeeccd2a1960c846a91575e926e70986c310b51efca
  Stored in directory: /root/.cache/pip/wheels/02/38/d5/2f54461050571bf5330fee2a37ab1c9b5e7540b0572f1acdab
  Building wheel for db (setup.py) ... done
  Created wheel for db: filename=db-0.1.1-py3-none-any.whl size=3893 sha256=6551a3e553d669d5b782ad28863b415200ab63f25dd0e3e87fad435490ea4ebb
  Stored in directory: /root/.cache/pip/wheels/8e/97/82/741d2b360507411ec233d0280d7371faa94b03bde834e4a9be
  Building wheel for antiorm (setup.py) ... done
  Created wheel for antiorm: filename=antiorm-1.2.1-py3-none-any.whl size=31678 sha256=66c6ed7b58b5725b88018ed55f64b99e580b8b54bfe362374c65d47706817275
  Stored in directory: /root/.cache/pip/wheels/c5/43/70/e9729370cfff40c49d3e3d05377d54b3ecd71f64e62341ea80
Successfully built db-sqlite3 db antiorm
Installing collected packages: antiorm, db, db-sqlite3
Successfully installed antiorm-1.2.1 db-0.1.1 db-sqlite3-0.0.1

In [5]:
import pandas as pd
import sqlite3
from datetime import date

In [12]:
#connecting with the database.
db = sqlite3.connect("fga_big_data.db")
db.execute("drop table if exists climate") # next data min 30 dari case
db.execute("create table climate (Tahun text,Populasi_Triliun integer,Kadar_CO2_ppm integer,Kadar_CH4_ppb integer,Kadar_N20_ppb integer,Suhu_Bumi_°C integer)")
# try:
#   db.execute("create table dataset(Tahun,Populasi,Energi Non-Ramah Lingkungan (eq. kg minyak/kapita),Energi Ramah Lingkungan (%energi total),Kadar CO2 (kT),Suhu Bumi (C))")
  #db.execute("create table user(id integer primary key, Mail text, Password text, Name text, Level text)")
# except:
#   print("Already table existed !!")

In [13]:
db = sqlite3.connect("fga_big_data.db")

In [16]:
# Menoba membuat 1 data utk tabel climate, lalu dimasukkan dalam fga_big_data.db

Tahun = "2020"
Populasi = 7.879
Kadar_CO2 = 380.01
Kadar_CH4 = 800.0
Kadar_N2O = 300.0
Suhu_Bumi = 1.02

cmd = "insert into climate(Tahun,Populasi_Triliun,Kadar_CO2_ppm,Kadar_CH4_ppb,Kadar_N20_ppb,Suhu_Bumi_°C) values('{}','{}','{}','{}','{}','{}')".format(Tahun,Populasi,Kadar_CO2,Kadar_CH4,Kadar_N2O,Suhu_Bumi)
db.execute(cmd)
db.commit()

# Querying

In [17]:
#Memanggil data yang baru saja dimasukkan ke dalam tabel

db = sqlite3.connect("fga_big_data.db")
rs = db.execute('SELECT * FROM climate')
for row in rs:
    print (row)

('2020', 7.879, 380.01, 800, 300, 1.02)

In [19]:
#Memanggil data yang baru saja dimasukkan ke dalam tabel dalam bentuk tabel dataset

db = sqlite3.connect("fga_big_data.db")
qry = """

SELECT * FROM climate

"""
df = pd.read_sql_query(qry, db)
df.head()

  Tahun  Populasi_Triliun  ...  Kadar_N20_ppb  Suhu_Bumi_°C
0  2020             7.879  ...            300          1.02

[1 rows x 6 columns]

# Meng-import data ke database

In [20]:
#Membuat method untuk memasukkan data external ke dalam database

def pushCSVdatasetToDB(Tahun,Populasi,Kadar_CO2,Kadar_CH4,Kadar_N2O,Suhu_Bumi):
#memasukkan niali variabel ke dalam tabel
    db = sqlite3.connect("fga_big_data.db")    
    cmd = "insert into climate(Tahun,Populasi_Triliun,Kadar_CO2_ppm,Kadar_CH4_ppb,Kadar_N20_ppb,Suhu_Bumi_°C) values('{}','{}','{}','{}','{}','{}')".format(Tahun,Populasi,Kadar_CO2,Kadar_CH4,Kadar_N2O,Suhu_Bumi)
    db.execute(cmd)
    db.commit()

In [23]:
data = pd.read_csv("climate_data.csv")
data.shape
data.head()

   Tahun  Populasi_(Triliun)  ...  Kadar_N20(ppb)  Suhu_Bumi(°C)
0   1968            2.882349  ...      315.883449       0.270950
1   1950            2.544770  ...      317.053544       0.194042
2   1984            4.637087  ...      283.286167       0.961167
3   2010            5.091307  ...      280.182223      -0.228254
4   1998            7.213058  ...      270.089516       0.705030

[5 rows x 6 columns]

In [31]:
#memasukkan 30 baris data dari climate.csv ke fga_big_data.db
for i in range(0,30):
  pushCSVdatasetToDB(data.iloc[i][0],data.iloc[i][1],data.iloc[i][2],data.iloc[i][3],data.iloc[i][4],data.iloc[i][5])

In [32]:
# Memanggil data yang baru saja dimasukkan dari csv ke db

db = sqlite3.connect("fga_big_data.db")
qry = """

SELECT * FROM climate

"""
df = pd.read_sql_query(qry, db)
df.head(50)

     Tahun  Populasi_Triliun  ...  Kadar_N20_ppb  Suhu_Bumi_°C
0   1968.0          2.882349  ...     315.883449      0.270950
1   1950.0          2.544770  ...     317.053544      0.194042
2   1984.0          4.637087  ...     283.286167      0.961167
3   2010.0          5.091307  ...     280.182223     -0.228254
4   1998.0          7.213058  ...     270.089516      0.705030
5   1956.0          6.163574  ...     304.956417      0.899575
6   1981.0          5.911488  ...     288.214072      0.400571
7   2014.0          5.619104  ...     311.281380     -0.399918
8   1965.0          5.691172  ...     329.585847     -0.070765
9   1988.0          3.521379  ...     284.428905      0.044809
10  1953.0          3.414418  ...     287.755144      0.257627
11  2013.0          7.168710  ...     282.460613      0.962062
12  1959.0          6.707967  ...     296.674111      0.767808
13  2007.0          7.400337  ...     281.244278     -0.404204
14  2000.0          3.402071  ...     318.692089      0.235482
15  2004.0          5.509150  ...     272.678497      0.720464
16  1979.0          7.319544  ...     305.488147     -0.238137
17  1966.0          4.718657  ...     329.780321      0.832350
18  2004.0          6.922762  ...     304.598374      0.466874
19  1958.0          5.608061  ...     291.338318      0.938624
20  1982.0          7.117420  ...     287.569918      0.697132
21  1962.0          4.116485  ...     327.392620      0.425092
22  1978.0          5.690423  ...     290.771934     -0.393935
23  2007.0          7.146390  ...     318.853277      0.056361
24  1955.0          4.867475  ...     272.120811      0.894625
25  1982.0          4.924171  ...     284.639650      0.169271
26  1993.0          6.681335  ...     300.552761      0.842399
27  2003.0          6.985331  ...     321.786041      0.867655
28  1967.0          6.297272  ...     297.398733     -0.278853
29  1957.0          5.341175  ...     314.336099     -0.181608

[30 rows x 6 columns]

In [33]:
#Mencoba perintah query delete

db = sqlite3.connect("fga_big_data.db")
cmd = """
DELETE FROM climate
"""
db.execute(cmd)
db.commit()

In [34]:
db = sqlite3.connect("fga_big_data.db")
qry = """
SELECT * FROM climate
"""
df = pd.read_sql_query(qry, db)
df.head(50)

Empty DataFrame
Columns: [Tahun, Populasi_Triliun, Kadar_CO2_ppm, Kadar_CH4_ppb, Kadar_N20_ppb, Suhu_Bumi_°C]
Index: []